version: '3.1'

services:
  db:
    image: public.ecr.aws/ubuntu/postgres
    container_name: notes_db
    restart: always
    environment:
      POSTGRES_DB: "notes"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
